### ISSUE TITLE
ImportError: No module named Modules.housekeeping

### ISSUE THREAD

**Issue by mtietjen27** [bartongroup/profDGE48#3]
Dear authors,

I attempted the generic_wrapper.py script as written in your documentation:

`./generic_wrapper.py -r ../DE_tool_scripts/edgeR.R -d ../testDGE/ -s ../Annotations/Saccharomyces_cerevisiae.EF4.68.gtf -b 10 -k 3 --precounts -r ../General/exclude_badreps.lst -o ../edgeRa/edgeR_k03.db -l ../edgeR_k03.log`

and got the following error message:

`File "./generic_wrapper.py", line 456, in <module> 
from Modules.housekeeping import custom_formatwarning 
ImportError: No module named Modules.housekeeping`

Could you tell me how I can solve this problem? 
Many thanks

**Comment by nickschurch** [comment]
It's probably just that you haven't added the path to the 'Modules' directory in your PYTHONPATH environmental variable. Try something like:

`export PYTHONPATH=/path/to/profDGE48/:/path/to/profDGE48/Modules/:$PYTHONPATH`

Also, make sure to take a look at the pre-compiled html help pages under `Doc/html` - there is information there on setting the right environment variables and making sure you have the right versions of things.

**Comment by mtietjen27** [comment]
Thanks - works fine now!
